### ISSUE TITLE
401 ao clicar em link para exemplo de PDF

### ISSUE THREAD

**Issue by renan-eccel** [UFSC/ufscthesisx#12]
quando clico no link [PDF](https://dl.dropboxusercontent.com/s/kevxtvs7bx9c8f7/main.pdf) apresentado na seção "[Modelo em PDF](https://github.com/UFSC/ufscthesisx#modelo-em-pdf)" do README.md um erro 401 do dropbox é gerado

**Comment by evandrocoan** [comment]
Você pode utilizar esse link: https://github.com/evandrocoan/ufscthesisx#modelo-em-pdf

Ele é da versão do meu fork. As mudanças feitas no meu fork estão para serem introduzidas aqui nessa pull request: https://github.com/UFSC/ufscthesisx/pull/11
