### ISSUE TITLE
Mudança para formato A4

### ISSUE THREAD

**Issue by renan-eccel** [UFSC/ufscthesisx#14]
A pouco tempo a  Resolução Normativa 17/2019/CPG foi publicada no dia 20 de maio de 2019, no Boletim Oficial da UFSC e destaca que o formato padrão para as teses e dissertações da UFSC deve ser A4. Ele também indica que existe um tutorial no website da BU, no entanto não encontrei nada com formato A4 em latex.

Vale destacar que esse formato estrará em vigor a partir do dia 1 de agosto.

Achei importante trazer essa informação.

**Comment by lucaspetry** [comment]
Link para a resolução normativa: http://propg.ufsc.br/files/2010/07/Resolu%C3%A7%C3%A3o-n.%C2%BA-17.2019.CPG-RN-Normas-para-Trabalho-de-Conclus%C3%A3o-de-Curso.pdf

Em resumo, as modificações no documento em si (recebido em lista de email):
1) formato passa a ser A4, observadas as normas de informação e de documentação da ABNT (“conforme tutoria disponibilizado pela BU/UFSC”);
2) no lugar da folha de aprovação, existirá a folha de certificação, com assinaturas (somente) do aluno, do orientador e do coordenador do PG (os membros da banca só assinam a ata da defesa…)
3) a capa dos trabalhos deverá seguir modelo disponibilizado pela BU/UFSC
