### ISSUE TITLE
Mudar conteúdo do modelo para igual ao da BU

### ISSUE THREAD

**Issue by lrsantos11** [UFSC/ufscthesisx#19]
Considerando o que conversei com a BU/UFSC e  também os modelos para TESE
https://repositorio.ufsc.br/handle/123456789/197457 e TCC https://repositorio.ufsc.br/xmlui/handle/123456789/174345 devemos modificar o conteúdo do modelo LaTeX para ficar igual ao da BU.

**Comment by evandrocoan** [comment]
Continuando a resposta em: https://github.com/UFSC/ufscthesisx/pull/18#issuecomment-549984242, vou também verificar esses documentos e aplicar as correções.

**Comment by lrsantos11** [comment]
@evandrocoan, você quer alguma ajuda? Por exemplo, posso ficar com a parte de mudar o texto mesmo (os modelos, etx). 
Você pode ficar com a parte dos programas lógicos mesmo!
To quase achando que é necessário um comando no ufscthesis.cls do tipo `true-false` determinando se é TCC ou se é Dissertação/Tese. Principalmente na folha de aprovação. 
Além disso, deveríamos deixar a Ficha de identificação da obra ser feita automaticamente pela BU e deixar o link pra include pdf. Podemos até fazer um pdf com essa informação, igual ao que está no TEMPLATE e @ usuári@ somente muda o PDF gerado.

**Comment by lrsantos11** [comment]
Você já viu isto: http://portal.bu.ufsc.br/files/2013/10/Template-Trabalhos-Academicos-UFSC-A4.zip

**Comment by evandrocoan** [comment]
> Você já viu isto: http://portal.bu.ufsc.br/files/2013/10/Template-Trabalhos-Academicos-UFSC-A4.zip

@lrsantos11, eu não tinha visto. Ele é um modelo bem recente. Depois que você me apresentou a ele, eu fiz integrei as mudanças dele, neste modelo, mas também criei um novo modelo: https://github.com/evandrocoan/ufscthesisx-light que é igual ao modelo do link http://portal.bu.ufsc.br/files/2013/10/Template-Trabalhos-Academicos-UFSC-A4.zip que você me apresentou, mas com a diferença ele usa o nosso arquivo `setup/ufscthesisx.cls`.

Então, agora temos dois modelos:
1. https://github.com/evandrocoan/ufscthesisx (esse aqui, cheio de conteúdos)
1. https://github.com/evandrocoan/ufscthesisx-light (igual ao da BU)

___
> Considerando o que conversei com a BU/UFSC e também os modelos para TESE
https://repositorio.ufsc.br/handle/123456789/197457 e TCC https://repositorio.ufsc.br/xmlui/handle/123456789/174345 devemos modificar o conteúdo do modelo LaTeX para ficar igual ao da BU.

Agora já temos um modelo igual ao da BU: https://github.com/evandrocoan/ufscthesisx-light que usa a mesma base que esse, o submódulo: ufscthesisx-setup

Você também pode fazer o fork o modelo https://github.com/evandrocoan/ufscthesisx-light para conta da ufsc no github. Nesse caso, também atualizo ele para utilizar o submodulo https://github.com/ufsc/ufscthesisx-setup, como feito na pull request https://github.com/UFSC/ufscthesisx/pull/20

___
> To quase achando que é necessário um comando no ufscthesis.cls do tipo true-false determinando se é TCC ou se é Dissertação/Tese. Principalmente na folha de aprovação.

Não seria necessário porque estes arquivos já devem ser editados pelos usuários para colocar os dados da banca, etc.


___
> Além disso, deveríamos deixar a Ficha de identificação da obra ser feita automaticamente pela BU e deixar o link pra include pdf. Podemos até fazer um pdf com essa informação, igual ao que está no TEMPLATE e @ usuári@ somente muda o PDF gerado.

Isso já é possível, basta editar o arquivo `beforetext/beforetext.tex` e não incluir a ficha catalográfica fake, e incluir o pdf:
```tex
\include{beforetext/fichacatalografica}
% trocar essa linha por um
\includepdf{Ficha_Catalografica.pdf}
```

De qualquer maneira, agora existem dois templates bem distintos um do outro, que devem servir de um bom exemplo (ufscthesisx e ufscthesisx-light). Depois, também vai ter o meu TCC quando eu publicar ele em março do ano que vem.


___
> você quer alguma ajuda? Por exemplo, posso ficar com a parte de mudar o texto mesmo (os modelos, etx).
Você pode ficar com a parte dos programas lógicos mesmo!

Acredito que eu já tenha terminado todas as correções com a pull request https://github.com/UFSC/ufscthesisx/pull/20. Se faltou alguma coisa, isso seria mais programação.
