### ISSUE TITLE
Falta criar os repositórios de images e setup no conta UFSC

### ISSUE THREAD

**Issue by evandrocoan** [UFSC/ufscthesisx#21]
Para que todo código deste template fique dentro da conta da UFSC, o arquivo `.gitmodules` foi atualizado.

De acordo com o arquivo: https://github.com/UFSC/ufscthesisx/blob/master/.gitmodules

Espera-se que a organização da UFSC no GitHub tenha um fork dos repositórios:
1. https://github.com/evandrocoan/ufscthesisx-images -> https://github.com/ufsc/ufscthesisx-images
1. https://github.com/evandrocoan/ufscthesisx-setup -> https://github.com/ufsc/ufscthesisx-setup

Caso contrário, ninguém novo consiguirá fazer alterações no template.

**Comment by evandrocoan** [comment]
Ping @josenorberto @robertosilvino

**Comment by josenorberto** [comment]
Feito! :)

**Comment by evandrocoan** [comment]
Valeu!

Eu também fiz um versão que eu chamei de `light` do template incluindo o template/conteúdo feito pelo funcionario da BU Alisson Lopes Furlani. Você pode fazer um fork dele também?

https://github.com/evandrocoan/ufscthesisx-light -> https://github.com/ufsc/ufscthesisx-light

**Comment by josenorberto** [comment]
Opa, feito o fork! :)

**Comment by evandrocoan** [comment]
Obrigado!

Acabei de terminar as últimas correções e abri 4 pull requets submetendo as atualizações:
1. https://github.com/UFSC/ufscthesisx/pull/22 - Correções e sistema de releases automáticos
1. https://github.com/UFSC/ufscthesisx-light/pull/1 - Correções no sistema de releases
1. https://github.com/UFSC/ufscthesisx-setup/pull/1 - Correções no template base
1. https://github.com/UFSC/ufscthesisx-images/pull/1 - Atualizar os PDF's de exemplo

Você pode também ativar o issue tracker dos novos repositórios? (Por padrão GitHub deixa eles desativados em forks)
1. https://github.com/UFSC/ufscthesisx-light/settings
1. https://github.com/UFSC/ufscthesisx-setup/settings
1. https://github.com/UFSC/ufscthesisx-images/settings

![image](https://user-images.githubusercontent.com/5332158/89231539-eec96c80-d5bb-11ea-8b7e-1e1b77d2cb32.png)

**Comment by josenorberto** [comment]
Olá! Pull requests aceitos e issue tracker habilitada nos projetos.
Abraço!

**Comment by evandrocoan** [comment]
Perfeito. A nova versão foi lançada automaticamente com sucesso para o `ufscthesisx` (https://github.com/UFSC/ufscthesisx/releases).

Infelizmente, aparentemente deu um bug no próprio GitHub e as nova versão do `ufscthesisx-light` https://github.com/UFSC/ufscthesisx-light/releases não pode ser criada.

Eu já reportei esse bug para eles nesse issue https://github.com/actions/runner/issues/653

Antes de tentar fazer uma gabiarra para tentar burlar esse bug/problema, vou esperar uns dias e ver se eles conseguem consertar isso.

Só para confirmar que isso é realmente um bug na parte do GitHub, você pode acessar essa página de configuração https://github.com/UFSC/ufscthesisx-light/settings/actions e confirmar que ela está igual a imagem a seguir?

![image](https://user-images.githubusercontent.com/5332158/89357937-49d09180-d698-11ea-93a1-87c2126ffd77.png)

**Comment by josenorberto** [comment]
Olá @evandrocoan, verifiquei que o https://github.com/UFSC/ufscthesisx-light/releases está aparecendo normalmente agora. A configuração já estava conforme a imagem que você enviou.

Qualquer coisa é só avisar! :)

**Comment by evandrocoan** [comment]
Olá @josenorberto 

Eu acho que descobri o problema. Você pode acessar essa página https://github.com/UFSC/ufscthesisx-light/actions e selecionar a opção `I understand my workflow, go ahead and enable them`?

![image](https://user-images.githubusercontent.com/5332158/89571643-64247f80-d7fe-11ea-9d32-16d09a3310dc.png)

Depois disso, basta fazer o merge da seguinte pull request https://github.com/UFSC/ufscthesisx-light/pull/3 para  a primeiro release ser feita.

**Comment by josenorberto** [comment]
@evandrocoan Feito! :)

**Comment by evandrocoan** [comment]
Valeu! A primeira versão foi lançada com sucesso: https://github.com/UFSC/ufscthesisx-light/releases

![image](https://user-images.githubusercontent.com/5332158/89663878-a60bff00-d8ac-11ea-998a-a426ae79e2ee.png)

**Comment by evandrocoan** [comment]
Somente percebi esse problema algora. Eu abri mais duas pull requests fazendo um correção nomes das versões:
1. https://github.com/UFSC/ufscthesisx-light/pull/4 - Changes the generated versions naming from 1.0.x to 1.1.x 
1. https://github.com/UFSC/ufscthesisx/pull/23 - Changes the generated versions naming from 1.0.x to 1.2.x

Isso vai evitar que algumas versões não sejam lançadas, uma vez que o nome da versão poderia coincidir com algum já existem.

**Comment by josenorberto** [comment]
@evandrocoan Merges realizados. :)
