### ISSUE TITLE
Dúvida: classe abnTeX2 customizada

### ISSUE THREAD

**Issue by la-costa** [UFSC/ufscthesisx#25]
Olá!

Estou conhecendo o projeto e tenho uma dúvida: por que o projeto usa uma classe customizada do abnTeX2?

Percebi isso porque estava tendo erros ao gerar o projeto em minha máquina (linux). Ao trocar a indicação da classe customizada pela classe que está nos pacotes do TeX Live, apenas fiquei com 1 erro na geração de uma tabela.

**Comment by evandrocoan** [comment]
Troquei a versão da ABNT por que tinha problemas com ela. Não tive nenhum erro ao usar o projeto. Quais erros você está tendo com essa versão?

Como você baixou o projeto? Você fez git clone ou usou botão do github? 
![image](https://user-images.githubusercontent.com/5332158/161170903-9e3fad47-cfce-48ab-9646-9a49f7faf6d3.png)

Para baixar corretamente, utilize https://github.com/UFSC/ufscthesisx/releases (demais botões de download não vão incluir todos os arquivos necessários, e você terá muitos erros)
![image](https://user-images.githubusercontent.com/5332158/161170836-59bc070b-3a11-4241-b272-38c968556cae.png)

Ele funciona no overleft com link disponibilizado (apresentado na imagem acima)?

**Comment by la-costa** [comment]
Oi @evandrocoan 

Eu usei o clone, que em tese seria a mesma versão desse release (não tinha percebido ele).

Quando troquei a classe abntex para a versão do TexLive fiquei somente com o erro do arquivo `intro.tex` no exemplo da tabela `tab:a_table_formatacao_de_texto`:

**Linha:** `\multicolumn{2}{p{\dimexpr\textwidth-2\tabcolsep\relax}}{\fonte{O autor -- \showfont} }`

**Erro:** `./chapters/intro.tex:116: Misplaced \noalign.`

Ele é gerado pelo comando `\fonte` e parece ser algo comum nos fóruns([Longtable Misplaced \noalign errors](https://tex.stackexchange.com/questions/348859/longtable-misplaced-noalign-errors) e [Spacing and fontsize from caption of longtable](https://tex.stackexchange.com/questions/638298/spacing-and-fontsize-from-caption-of-longtable)), entretanto não achei ainda uma forma de resolver (exceto retirar o comando).

Já com o pacote zip que você indicou, obtive o mesmo erro que estava obtendo no clone:

**Erro:** `./chapters/intro.tex:116: Undefined control sequence.`

Para inibir esse erro (e os próximos que são gerados em outros `caption`), só se eu inibir algumas linhas do `\fonte` da classe customizada.

**Comment by evandrocoan** [comment]
Olá. Obrigado pelos detalhes. Eu subiu um docker com Ubuntu 22.04 e Tex Live 2022:
1. `docker run -it ubuntu:22.04 bash`
1. `apt get update`
1. `apt update`
1. `apt install texlive-full`
1. `apt install git build-essential`
1. `exit`
1. `docker ps -a` (lista imagens recentes para ver id da última)
1. `docker commit bd542d616051 latextest` (salva imagem anterior como latextest)
1. `git clone --recursive https://github.com/UFSC/ufscthesisx`
1. `docker run -v /home/user/ufscthesisx/:/ufscthesisx/ -it latextest bash`
1. `cd /ufscthesisx`
1. `make thesis debug=1`

Com isso consegui reproduzir o mesmo problema. Parece que desde que eu trabalhei nesse template em 2019, teve uma atualização de alguma biblioteca do latex que usamos e isso quebrou o comando `\fonte`. Como correção para esse erro agora, você pode aplicar essa alteração na classe `abntex2`:
```diff
--- a/abntex2.cls
+++ b/abntex2.cls
@@ -147,9 +147,9 @@
      % \setlength{\abovecaptionskip}{10pt}
      \setlength{\belowcaptionskip}{4pt}
      \ABNTEXfontereduzida
-     \captiondelim{\ABNTEXcaptionfontedelim}
+     % \captiondelim{\ABNTEXcaptionfontedelim}
      % https://tex.stackexchange.com/questions/515460/misplaced-noalign-captionsetup-noalign-when-using-captionsetup-inside-mem
-     \caption@setlabelseparator{colon}%
+     % \caption@setlabelseparator{colon}%
      \@makecaption{\ABNTEXfontereduzida #1}{\ignorespaces\ABNTEXfontereduzida #2}\par
   \endgroup}
```

Esse patch não é solução definitiva pois os labels do comando fonte vão usar dash `--` em vez de dois pontos `:`:
![image](https://user-images.githubusercontent.com/5332158/161409317-b9f82be3-63ec-4b4a-9c80-284aee884ef3.png)

Mas você pode usar esse patch até conseguirmos descobrir como corrigir isso. Depois o ideal vai ser também enviar parte dessa correção para classe oficial da abntex2, pois eles também tem problema com ela. A diferença é que a nossa versão da abntex2 tem mais modificações e foi mais afetada.

Fiz compilação agora depois desse patch e não tive mais errors. Esse são meus logs completos: [latexfulllog.txt](https://github.com/UFSC/ufscthesisx/files/8403737/latexfulllog.txt).

**Comment by evandrocoan** [comment]
@la-costa , abri uma pull-request com a correção #26

Hoje você pode aplicar a correção manualmente na sua classe abntex2:
```diff
--- a/abntex2.cls
+++ b/abntex2.cls
@@ -147,9 +147,13 @@
      % \setlength{\abovecaptionskip}{10pt}
      \setlength{\belowcaptionskip}{4pt}
      \ABNTEXfontereduzida
-     \captiondelim{\ABNTEXcaptionfontedelim}
+     % \captiondelim{\ABNTEXcaptionfontedelim}
      % https://tex.stackexchange.com/questions/515460/misplaced-noalign-captionsetup-noalign-when-using-captionsetup-inside-mem
-     \caption@setlabelseparator{colon}%
+     \ifdefined\caption@setlabelseparator
+       \caption@setlabelseparator{colon}%
+     \else%
+       \caption@set{labelseparator}{colon}%
+     \fi%
      \@makecaption{\ABNTEXfontereduzida #1}{\ignorespaces\ABNTEXfontereduzida #2}\par
   \endgroup}
```

O problema aconteceu porque pacote latex caption renomeou o comando que eu estava usando de `caption@setlabelseparator` para `caption@set{labelseparator}` na commit: https://gitlab.com/axelsommerfeldt/caption/-/commit/a9a968f976865fd617f4f431e5b4b2ebdd0b0882?page=4#791450f831b92438f900ff0b01fbce50725be9f7_680_654

Usualmente pacotes latex não fazem isso, mas como eu estava usando uma função interna do pacote, tivemos essa quebra. Usei essa função mais interna do pacote caption para contornar o erro de compilação que você viu ao usar o pacote abntex2 oficial.

Vi outros warnings como `Use of uninitialized value within %Biber::Config::CONFIG_OPTSCOPE_BIBLATEX in hash dereference at /usr/share/perl5/Biber/Config.pm line 972`, mas eles parecem que vão ser concertados na próxima versão do biber: https://github.com/plk/biber/issues/403

**Comment by evandrocoan** [comment]
Olá, @josenorberto 

Eu acabei de fazer os últimos ajustes que faltavam para resolver esse caso. De acordo com @la-costa , a solução parece ok.

Você pode fazer merge dessas pull-requests para lançar a correção?
1. https://github.com/UFSC/ufscthesisx-setup/pull/2 
1. https://github.com/UFSC/ufscthesisx/pull/26
1. https://github.com/UFSC/ufscthesisx-light/pull/7

O sistema irá lançar uma nova versão automaticamente em
1. https://github.com/UFSC/ufscthesisx/releases
1. https://github.com/UFSC/ufscthesisx-light/releases

Caso tenha algum problema ou precisa de ajuda é só avisar que eu estou disponível.
