### ISSUE TITLE
Error Overleaf V2 

### ISSUE THREAD

**Issue by djackR** [UFSC/ufscthesisx#7]
Não consegui importar o template para a Overleaf V2, funciona  na V1 mas  não na V2.

![over](https://user-images.githubusercontent.com/20249585/49116720-a81f5d00-f285-11e8-8afb-0cae1e24f90f.png)

**Comment by lucaspetry** [comment]
Estou com o mesmo problema.

**Comment by evandrocoan** [comment]
Se funciona com Overleaf V1 mas não funciona mais na V2, a Overleaf quebrou alguma coisa. Eles em um issue tracker? Isso poderia ser reportado a eles?

E executando localmente com make funciona? Antes de executar, acredito que precisa-se ter instalado alguns pacotes latex como abntex2, etc.

**Comment by lucaspetry** [comment]
Consegui resolver o problema aparentemente.

No `main.tex`, troquei a linha:
`\input{setup/utilities}`
por
`\input{setup/utilities.tex}`

Normalmente a extensão `.tex` pode ser omitida no input, mas eu acredito que o compilador se confunde pois existe uma pasta chamada `utilities` dentro do `setup` também. Acho que ficaria melhor mudar o nome do arquivo ao invés de colocar o .tex para evitar confusões futuras. Abri o PR #9 com essa modificação.

**Comment by evandrocoan** [comment]
Valeu!
