### ISSUE TITLE
Adicionar resumo expandido

### ISSUE THREAD

**Issue by lehmann** [UFSC/ufscthesisx#8]
Desde 2017, as teses escrita em idioma estrangeiro devem conter o Resumo expandido.
Este resumo contém uma pequena estrutura interna e ao tentar fazer o texto nesta estrutura, estou tendo dificuldades inclusive em compilar meu LaTeX.
Adicionar ao template uma seção para o Resumo Expandido é essencial, já que muitas teses são escritas em idioma estrangeiro.

**Comment by evandrocoan** [comment]
A parte que cria o abstract é um comando especializado que faz a remoção agressiva de vários elementos de formatação do texto para forçar um abstract padronizado. Para implementar essa novo abstract com estrutura, o comando atual para o abstract estrangeiro, vai ter que ser removido, e um novo comando criado, ou talvez deixar o usuário diretamente fazer a formatação sem qualquer restrição.

Você pode compartilhar o código que você tentou compilar e o modelo ou fonte do modelo de como deve ser esse novo abstracts para estrangeiros?

Mais tarde esse ano (maio/2019) vou ter que entregar a minha tese (a não ser que eu não consiga terminar e fique para outubro/2019), dai eu já poderia fazer a implementação desse abstract. Eu não estava afim de mexer com latex agora. Por enquanto estou cansado be brigar com latex. Prefiro terminar de escrever a tese antes de me incomodar com erros de compilação.

Para quando você precisa ter isso implementado?

**Comment by lehmann** [comment]
Eu tentei fazer a estrutura de forma bem rudimentar, utilizando \section*{} mesmo, mas daí sempre o LaTeX reclama de "Something's wrong--perhaps a missing \item."
Eu me conformei com isso e resolvi utilizar de \break's e \textbf's.
Agora, descobri que também não é possível utilizar um itemize, mesmo sendo um itemize bem formato.

Precisar eu precisaria para agora, mas quem sou eu para cobrar algo de alguém no GitHub né?!
Também estou cansado de brigar com o latex, e isso que eu usei esse teu template, que já me poupou muito tempo.

Link para a definição do formato do resumo expandido: http://portal.bu.ufsc.br/files/2013/10/RESUMO-EXPANDIDO.docx
